### ISSUE TITLE
Motion detector work

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#100]
andy ordered 1 for jimmy on Friday – backordered until april

ordered these instead:
http://shop-orbbec3d-com.3dcartstores.com/Orbbec-Astra_p_12.html

**Comment by AudreyTheIndustrious** [comment]
C&A has two of them. Andy working on ordering and getting them to TI before leaving for Europe.

**Comment by AudreyTheIndustrious** [comment]
one camera arriving tomorrow for Jimmy. three cameras arriving Thursday for Sara.

**Comment by AndyTheIndustrious** [comment]
Hello.

We should discuss on our call this morning how we will tell the client about the change in camera. This might cause an issue both with power and mounting.

Andy

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Mar 6, 2018, at 11:20 PM, Audrey Sniezek <notifications@github.com<mailto:notifications@github.com>> wrote:


one camera arriving tomorrow for Jimmy. three cameras arriving Thursday for Sara.

**Comment by AudreyTheIndustrious** [comment]
Jimmy got the motion detector camera software installed.
