### ISSUE TITLE
Install logmein for remote capabilities

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#105]
Andy to install on machines, Robin to connect them to the network, Jimmy to remote install software.

Chris Reid to provide 2 logmein licenses

**Comment by AndyTheIndustrious** [comment]
Hello!

I have installed the remote access software but need to test it.  I have to leave the building to test it.  But we are in good shape.

Thank you.

Andy

**Comment by AudreyTheIndustrious** [comment]
Tested and verified.
