### ISSUE TITLE
Find Call list for analytics from NGoar for Jimmy

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#106]
@AndyTheIndustrious is the .dll delivered from Ngoar recently considered the call list? Or, do you have something more to deliver for Jimmy. 

https://www.dropbox.com/s/czquo84w2kfngx0/C%26A%20NSC%20Digital%20Traffic%20Drivers%20Analytics%20Scope%2020November2017.pdf?dl=0

**Comment by AudreyTheIndustrious** [comment]
@JimmyMooreTheIndustrious is this what Sergey has delivered to you? can i close this out?

**Comment by AudreyTheIndustrious** [comment]
@AndyTheIndustrious is the .dll delivered from Ngoar recently considered the call list? Or, do you have something more to deliver for Jimmy.

**Comment by AndyTheIndustrious** [comment]
Hi.  I don’t know what this means.

The DLL is the library that lets Jimmy get measurements into the database over the internet.

The call list is the business requirements of what is measured so that Jimmy can put them into the application when events occur.

Jimmy has both.

Andy

**Comment by AudreyTheIndustrious** [comment]
Great! Thanks!


On Feb 26, 2018, at 09:40, AndyTheIndustrious <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi. I don’t know what this means.

The DLL is the library that lets Jimmy get measurements into the database over the internet.

The call list is the business requirements of what is measured so that Jimmy can put them into the application when events occur.

Jimmy has both.

Andy
