### ISSUE TITLE
Write request to use video equipment for photoshoot

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#108]
Creating a task to track the request

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious 

We would like to capture some stills of each experience during the video shoot. We will have a photographer present to shoot, and would like to take the shots at the end of filming each interactive. Ideally we would keep the lighting setup the same, but if that is an issue, please advise so we can plan accordingly.

**Comment by AndyTheIndustrious** [comment]
Complete.

Thank you.
