### ISSUE TITLE
Overnight serial cable for scanner to Robin before Beta

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#110]

**Comment by AndyTheIndustrious** [comment]
Hello!  Am I able to set a reminder on this please?

Maybe I could get a reminder on Monday?

Andy

**Comment by AudreyTheIndustrious** [comment]
Try this.
[cid:image002.jpg@01D3AB4F.60A97240]

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
Here's your reminder @AndyTheIndustrious . Please overnight the serial cables to Robin. :)

**Comment by AudreyTheIndustrious** [comment]
Wrong part, reordering. (Feb 25)
