### ISSUE TITLE
Hero outfit for DD

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#111]
@AndyTheIndustrious @saratheindustrious Do we have this for the beta? Is it placeholder outfit we picked or production outfit that we'll use at the launch?

**Comment by AndyTheIndustrious** [comment]
Hi. What's this ticket?

Is this to choose the outfits for DD Interactive? I think we do need a plan for that, right?

Andy


Andy Austin
President / The Industrious
mobile // +1.323.736.2121
mobile // +44.(0)7454.572.928

________________________________

**Comment by AudreyTheIndustrious** [comment]
That’s the question I was asking back at you. 😊 I think we have an outfit we picked for the beta and C&A haven’t given us the hero outfit they want to use for launch. Wasn’t sure if there was an action item here for you or sara or me with Jennifer/Robin. And, wanted clarity that this is not a priority for beta.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
OK. Perfect.

Absolutely not a priority for beta.

To add to the asset tracker, we need photography of been 10 and 30 outfits from each of the four collections to put into DD Interactive. For each outfit, we need the URL for each garment or the product ID so we (you) can make the QR-codes.

Make sense?

Andy


Andy Austin
President / The Industrious
mobile // +1.323.736.2121
mobile // +44.(0)7454.572.928

________________________________

**Comment by AudreyTheIndustrious** [comment]
Got it, thanks!

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
There are 3 examples for Monday in this video loop. https://www.dropbox.com/s/n7n8njo44tcjk9w/DD-Beta.mov?dl=0

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndyTheIndustrious** [comment]
They look outstanding.

Andy

**Comment by AudreyTheIndustrious** [comment]
We agreed to use the WttW hero outfits for DD. closing this out.
