### ISSUE TITLE
Define default products for Browse C&A

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#115]
@saratheindustrious please explain. :)

**Comment by saratheindustrious** [comment]
I don't know what this means.

**Comment by AudreyTheIndustrious** [comment]
More context: If someone scans a price tag that isn't in the system, we will say "sorry we can't find that, but here are some great products to check out."

**Comment by saratheindustrious** [comment]
Ok – do we have to have set products, or can it just randomize? I’m concerned if we choose 5 now, those may change before launch and certainly will post-launch.

**Comment by AudreyTheIndustrious** [comment]
Good question, let’s add @Andy Austin<mailto:andy@wearetheindustrious.com> This was all the information I have at the moment.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
That is a good question.

I don’t know if randomize will work.  I’ll ask the development team.

Thank you!  I’ll copy you on the request.

Andy

From: Audrey Sniezek
Sent: Thursday, February 22, 2018 10:30 AM
To: TheIndustrious/CandA <reply@reply.github.com>; TheIndustrious/CandA <CandA@noreply.github.com>; Andy Austin <andy@wearetheindustrious.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [TheIndustrious/CandA] Define default products for Browse C&A (#115)

Good question, let’s add @Andy Austin<mailto:andy@wearetheindustrious.com> This was all the information I have at the moment.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
https://www.dropbox.com/s/hzxpkn6fw7n1q9x/Browse%20C%26A%20Default%20items%20per%20division_20180316.xlsx?dl=0
