### ISSUE TITLE
IP addresses and Domains for Ngoar

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#120]
@AndyTheIndustrious 
Praj will be sending us a list but we probably won't see it until just before our meeting with them tomorrow. They are waiting on the following from us:

1. IP addresses for whitelisting
2. Domain names (for Live catalog API)
3. requirement for HTTPS Cert needed for Catalog API for IG (confirm this is required or not)
4. Live IG account details from C&A (C&A person to authorize)
5. Domain name for IG (internal, not for end users)

Update (Feb 25)
1.	IP addresses for whitelisting – Andy is working on this
2.	Domain names (for Live catalog API) - Boris has this. Andy gave him his GoDaddy login so he could set everything up. Andy did this two weeks ago.
3.	requirement for HTTPS Cert needed for Catalog API for IG (confirm this is required or not) – Andy did not understand this requirement and I could not elaborate better. Asked Praj to clarify
4.	Live IG account details from C&A (C&A person to authorize) - Andy already gave Ngoar C&A’s Instagram login, please investigate and confirm receipt. See ticket #28
5.	Domain name for IG (internal, not for end users) – Andy did not understand this requirement and I could not elaborate better. Asked Praj to clarify

**Comment by AndyTheIndustrious** [comment]
1.  I need to get
  2.  Boris has this.  I gave him my GoDaddy login so he could set everything up.  I did this two weeks ago.  Do I need to call Peter at Ngoar because shit like this keeps falling through the cracks?
  3.  Not sure what this is.
  4.  I already gave Ngoar C&A’s Instagram login.
  5.  Not sure what this is.

Thank you!

Andy

**Comment by AudreyTheIndustrious** [comment]
Good input. You don’t need to call Peter just yet. 😊 We’re meeting with Ngoar tomorrow. I’ll update Praj and she can work to make sure we have the latest requirements and updates for our meeting later that day.  When will you have the IPs? Do you have a record of the IG login that I can reforward or reference?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
The Instagram account credentials are in their crappy project management system in ticket number 28.

I’ll work on the IP ranges now.

Thank you.

Andy

**Comment by AudreyTheIndustrious** [comment]
Ok, great. I’ll make sure they see it.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
I think I’m going to have to call Peter.  He and I had a 90 minute conference call on Saturday morning at 5:30 am that some of the projects are overrunning on hours.  This is exactly why.

**Comment by AudreyTheIndustrious** [comment]
Do you think it would be helpful to wait until you see and talk to the team regarding the latest plans?

From the meeting today, they have 4 hours of dev time left for the kids game assets. Probably 1 hour on the update to the analytics .dll (to move from dev environment to production environment, no logic changes) and they are actively working on html piece as the final tsk for WttW mobile shopping list. They will demo/walkthrough WttW mobile shopping list in tomorrow’s call.

The only remaining outstanding items were those 5 bullets of which only 2 need clarification and 1 action item is with you.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Well – we are going to show Robin no WttW mobile shopping list tomorrow.  That stinks.

Looking forward to the call.

Andy

**Comment by AudreyTheIndustrious** [comment]
Got it. Yeah, that stinks.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
live credentials for instagram provided by Andy don't seem to work now. Probably, C&A might have changed them. Could you please followup C&A or would you like me to do it?

**Comment by AndyTheIndustrious** [comment]
Rats.  Would you please work that out with Robin?

Thank you.

Andy
