### ISSUE TITLE
WTTW - Functionality - Close nav menu after selection

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#129]

**Comment by AudreyTheIndustrious** [comment]
I see the drawer opening but not able to swipe it closed again, did you see this? Is that this remark? Is there a newer build than .05?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
This item is about the menu to select the different collections, not the drawers.



Sara Giessen
Creative Director / The Industrious
mobile // 770.656.0033
web // wearetheindustrious.com
