### ISSUE TITLE
Request loading animation

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#132]
Browse C&A - add a loading animation to each product image spot before it loads

Let me know if you need a specific design for this. Should just something along the lines of a nice spinning GIF.

**Comment by AudreyTheIndustrious** [comment]
Can you provide a sample? I don’t trust Ngoar to do something intuitively appropriate.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
Okay it will take some time to design. Maybe we can go ahead and give them a heads up about the functionality and say we will provide a GIF later.

**Comment by AudreyTheIndustrious** [comment]
That will work. Maybe we can have it by the end of the week for them?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
[Let's ask them to use this this loader.](https://loading.io/spinner/rolling/-curve-bars-loading-indicator#) The "color" field should be c3002f.

**Comment by AudreyTheIndustrious** [comment]
#99: Browse C&A - add a loading animation to each product image spot before it loads in AC says this is resolved.
