### ISSUE TITLE
Wttw - unable to close the drawers from within a drawer

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#134]
@JimmyMooreTheIndustrious 
press + to open the drawer
swipe to end of drawer, then swipe back to the beginning
there is no way to close the drawer, user must press outside the drawer to close it and that is not intuitive

**Comment by saratheindustrious** [comment]
Proposed interaction: 
When the state is at the very first position, if you swipe to the right it closes the drawer. Basically the reverse of the open swipe gesture.

**Comment by AudreyTheIndustrious** [comment]
punted, per @AndyTheIndustrious . He notes that drawers staying open is fine for this release. Mar 8 meeting.
