### ISSUE TITLE
WttW - "are you still there"

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#136]
@JimmyMooreTheIndustrious 
1. the 'are you still there' text can come earlier (about 15 seconds before displaying it would be good)
2. once the 'are you still there' text appears the system crashes if you dont acknowledge you are in fact still there

**Comment by saratheindustrious** [comment]
I believe question 2 is because your computer isn't in kiosk mode, but I will let Jimmy confirm.

**Comment by AudreyTheIndustrious** [comment]
rosie will handle #2 per Andy. #1 we will have to note for setup.
