### ISSUE TITLE
Video elements from Rob for launch

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#140]
### Window to the Worlds
- [x] Attract Loop - Damen
- [x] Attract Loop - Herren
- [x] Attract Loop - Kinder
- [x] Attract Loop - Clockhouse

### Browse C&A
- [x] Attract Loop - Damen
- [x] Attract Loop - Herren
- [x] Attract Loop - Kinder
- [x] Attract Loop - Clockhouse

### Discover Digital
- [x] DD Interactive callout video
- [x] C&A Famous Instagram video background
- [x] DD Look videos - Damen (4)
- [x] DD Looks videos - Herren (3)
- [x] DD Looks videos - Kinder (4)
- [x] DD Looks videos - Clockhouse (8)

**Comment by saratheindustrious** [comment]
Currently waiting on final translation elements before requesting final versions for approval. After we receive translations, will request from Rob. Then will post final videos to Vimeo and send to Robin for approval.

**Comment by saratheindustrious** [comment]
@JimmyMooreTheIndustrious There are four attract loops in Deliver for you; one for each version of the app.
Design/04_Deliver/WTTW/attracts/

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious The videos for DD Interactive are here:
Projects/C&A/Design/04_Deliver/DD/Interactive

**Comment by AudreyTheIndustrious** [comment]
FYI, I Noticed that DD-Clockhouse-5.mov, the QR codes are referring to the wrong products (ie. Shirt is QR image is pointing to the jacket and the Jacket QR code is pointing to the shirt, when you scan the QR for the jacket you get the product page for the shirt, and same for the shirt, scan the qr code and get the page for the jacket).

All others look good.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
Verified clockhouse 5 QR codes are correct.
