### ISSUE TITLE
Feedback from Release 103

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#141]
- [ ] It's crashing a lot for me
- [ ] There are German translations in their Dropbox that should be used _(Browse-cr5.psd)_
- [ ] The background of the bar doesn't match the background of the images. I'm hoping #f7f7f7 will work but if not, we should discuss...
- [ ] Add loaders throughout
- [ ] When i put in a "wrong" number it shows the "complete the look" before showing the error background.
- [ ] The bolder fonts look bad

**Comment by AudreyTheIndustrious** [comment]
@saratheindustrious just checking, this is for Ngoar, right?

**Comment by saratheindustrious** [comment]
It is. Not sure if we should send it yet but I wanted to capture my initial catches

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AudreyTheIndustrious** [comment]
These should be resolved by now. please confirm. @saratheindustrious
