### ISSUE TITLE
Further Clockhouse photography

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#142]
@saratheindustrious from Jenni
In case we need more Clockhouse images, I just received a WeTransfer link by our brand campaign manager. 

https://we.tl/JNounMHUs9 

We are allowed to show them in store too. 

Yours sincerely, 
Jenni

**Comment by saratheindustrious** [comment]
I downloaded this this morning. We had most of the images already and I added the new shots to _Projects/C&A/Design/01_Assets/Imagery/Clockhouse/2-non-top-stores-saisonal_
