### ISSUE TITLE
DD - Two versions of attract loop (1 touch, 1 without touch)

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#148]
we now have quantity (2) Discover Digital at the store.  (So ugly.)  One is interactive and one is not.  So we need two versions of the main loop please, one with a CTA to touch and one without a CTA to touch.

**Comment by saratheindustrious** [comment]
The original plan was to have Rob export each of the video pieces separately and then we would assemble them in the digital signage player. So **WE** would be able to define which elements display. @AndyTheIndustrious is this still the plan? OR should we simply render 2 looping videos?

**Comment by AndyTheIndustrious** [comment]
That is the plan!

Thank you.

**Comment by saratheindustrious** [comment]
I think this is done. Rob will deliver the video elements separately and Andy has laid out the flow for each of the two videos.

**Comment by AndyTheIndustrious** [comment]
Thank you.

Yes – we will build the separate elements into the individual machines.  Glad we were tracking this.

Andy
