### ISSUE TITLE
Create QR codes for Discover Digital Interactive

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#151]
Audrey,
Andy said you would be generating the QR codes for the discover digital interactive videos. The codes I have as of now are in [the spreadsheet 18-0305-ProductCodes.xlsx in the 00_Reference folder.](https://www.dropbox.com/s/9c46ly7zii1xl3p/18-0305-ProductCodes.xlsx?dl=0) The products in the hero photos – "key products" – are labeled Row 1 on each pic.

There are some key products that aren't online yet. They are highlighted in orange in the spreadsheet. Could you please look and see if there is something like bit.ly that we could use as the link for those QR codes? If so, we could direct it to canda.com for now and then replace the redirect URL when those items come online.

I made some subfolders where you can place the QR images: Projects/C&A/Design/01_Assets/QR-Beta/Production.

If you have any questions please let me know!
Thanks!
SHG

**Comment by AudreyTheIndustrious** [comment]
You read my mind! I was just about to inquire about this. :)

**Comment by saratheindustrious** [comment]
I’m realizing that since we include the name of the product and price in the videos, it’s probably not worth it to do the interim link for the ones that aren’t live yet: we’d have to update the video anyway.

**Comment by AudreyTheIndustrious** [comment]
I am ready to start generating the QR codes. Some questions: what size, resolution, error correction and image format would you like? I have a short url and the long url to offer. these will be dynamic QR codes meaning we can change the url at anytime without changing the QR image.

![image](https://user-images.githubusercontent.com/36212831/37012541-131dbca4-20aa-11e8-8299-a5a9a642b2d1.png)

error correction:
There are 4 error correction levels used for QR codes, with each one adding different amounts of “backup” data depending on how much damage the QR code is expected to suffer in its intended environment, and hence how much error correction may be required:

Level L – up to 7% damage
Level M – up to 15% damage
Level Q – up to 25% damage
Level H – up to 30% damage

So here are the take-outs:

The lower the error correction level, the less dense the QR code image is, which improves minimum printing size.
The higher the error correction level, the more damage it can sustain before it becomes unreadabale.
Level L or Level M represent the best compromise between density and ruggedness for general marketing use. 
Level Q and Level H are generally recommended for industrial environments where keeping the QR code clean or un-damaged will be a challenge.

![image](https://user-images.githubusercontent.com/36212831/37012615-6eade68e-20aa-11e8-9ae6-caea88326b82.png)

**Comment by AudreyTheIndustrious** [comment]
I made some QR codes using the following:
3000 pixels
300 dpi
Medium error correction
output is .eps.

**Comment by AudreyTheIndustrious** [comment]
All QR codes have been generated based on what I understood would be the right format. Have a look and let me know if I need to regenerate any. Also, I made changes to the spreadsheet to assist with this generation. If you can work from that version, great, if not, no worries. All deltas just need to be called out.

thanks!

**Comment by saratheindustrious** [comment]
Ok I've pulled the ones that are available for Discover Digital and sent them to Rob. There are 16 more that as of this morning aren't online yet. I'll let you know when those product links are available.

**Comment by AudreyTheIndustrious** [comment]
I don’t know why I thought I had to create QR codes for the drawers and looks, too….but I did. Sorry if you didn’t need them? They are in their respective folders on that share, in case you do.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
done. may need additional in time.

**Comment by saratheindustrious** [comment]
I'm going to reopen just to keep it on my own radar. We can't complete the videos for the app without (at least most of) the remaining ones, marked here in red.

<img width="990" alt="screen shot 2018-03-07 at 8 12 31 am" src="https://user-images.githubusercontent.com/36420298/37094002-617c83f4-21df-11e8-9da1-56ce63e270a5.png">
<img width="987" alt="screen shot 2018-03-07 at 8 12 36 am" src="https://user-images.githubusercontent.com/36420298/37094003-618fbec4-21df-11e8-9e99-d784722db9c6.png">
<img width="987" alt="screen shot 2018-03-07 at 8 12 43 am" src="https://user-images.githubusercontent.com/36420298/37094004-61a180be-21df-11e8-8b26-ecbe1f03ff32.png">
<img width="987" alt="screen shot 2018-03-07 at 8 12 48 am" src="https://user-images.githubusercontent.com/36420298/37094005-61c23afc-21df-11e8-9a4d-eb800088e444.png">

**Comment by saratheindustrious** [comment]
Hey @AudreyTheIndustrious  - we got a few more products to QR-ify. They are updated in the 18-0308-ProductCodes Excel.
Herren Hero 1 - Jacket
Herren Hero 3 - Jacket
Clockhouse Hero 4 - Bottoms
Clockhouse Hero 5 - Jacket
Clockhouse Hero 5 - Tee
Clockhouse Hero 7 - Jumpsuit

**Comment by saratheindustrious** [comment]
Editing with one more we got from Jenni:
Herren Hero 1 - Jacket
Herren Hero 3 - Jacket
Clockohuse Hero 1 - Top
Clockhouse Hero 4 - Bottoms
Clockhouse Hero 5 - Jacket
Clockhouse Hero 5 - Tee
Clockhouse Hero 7 - Jumpsuit

**Comment by AudreyTheIndustrious** [comment]
done.
