### ISSUE TITLE
Browse C&A - Remaining assets to provide to Ngoar

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#153]
- [x] Attract Loop (6-Mar – Rob is working on this)
- [x] Updated sustainability PSD (6-Mar – emailing back and forth w/ Jenni for approval; make note of line-spacing when sending)
- [x] Sustainability video (6-Mar – on their dropbox, waiting to notify with rest of this batch [Design/Assets/Video-BrowseCA-Sustainability/171205_CA_Sustain_09_Subs VO.wmv](https://www.dropbox.com/s/75iy6jlca7v1uld/171205_CA_Sustain_09_Subs%20VO.wmv?dl=0))
- [x] Updated foundation PSD  (6-Mar – emailing back and forth w/ Jenni for approval)
- [x] Foundation video (6-Mar – waiting to hear from Foundation team if we can use a single video; may scrap this if necessary)

**Comment by saratheindustrious** [comment]
notes on build 106
- new attract (shg to send)
- new sustainability content/vid (shg to send)
- new foundation content/vid (shg to send)
- longer timeout
- add timeout screen
- check Farbe and Grobe font; doesn't look as nice as the others

**Comment by AudreyTheIndustrious** [comment]
@saratheindustrious I know you've been busy. I think you checked off everything on the list above, correct? What's left, if not?
