### ISSUE TITLE
product names cut off in text boxes

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#167]
![image](https://user-images.githubusercontent.com/36212831/37370467-95ea6cc0-26c9-11e8-84de-bd43a22704b6.png)
![image](https://user-images.githubusercontent.com/36212831/37370500-a706b23e-26c9-11e8-9e22-b25d21b6ab13.png)

German sample text to test: 
Baukasten-Sakko
Jogginghose

**Comment by jimmyism-1** [comment]
FIXED
