### ISSUE TITLE
Define final content for Shelfmaster

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#17]

**Comment by AudreyTheIndustrious** [comment]
reqeusting Spring ladies video from Jennifer

**Comment by AndyTheIndustrious** [comment]
We will take either the spring LDiv video or the #WearTheChange video.  We have requested both.

Thank you.

Andy

**Comment by AudreyTheIndustrious** [comment]
We received #wearthechange video from Jennifer and it's in Edward's hands to install.
