### ISSUE TITLE
Clockhouse Hero 1, Jacket is wrong link/details/QR

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#181]
I have updated the Excel doc, but I'm not sure if this affects the actual build of WTTW.

Also I will need a QR code with the right link.

**Comment by AudreyTheIndustrious** [comment]
Saw you fixed the link, thank you. I fixed the QR and put it in the folder https://www.dropbox.com/sh/wste4b8m040vzpp/AAA_KdLUPelhe-83t8RHgtlVa?dl=0

This does not affect WTTW
