### ISSUE TITLE
Robin to receive Shelfmaster hardware

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#19]
@AndyTheIndustrious did you get this? Will be demo this with the beta reveal?

**Comment by AudreyTheIndustrious** [comment]
Isreali team will program shelfmaster over the wire... Andy? Robin? will get it Wed/Thu.

**Comment by AudreyTheIndustrious** [comment]
Edward has shelfmaster. Need to get it to Robin.

**Comment by AndyTheIndustrious** [comment]
Hello.

Edward forgot it.

He will ship it to the store once we get the content on it.

Thank you for reminding me.

Andy


Andy Austin
President / The Industrious
mobile // +1.323.736.2121
mobile // +44.(0)7454.572.928

________________________________

**Comment by AudreyTheIndustrious** [comment]
Shelfmaster delivered
