### ISSUE TITLE
Digital Signage playlist

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#3]
Ability to submit IG posts for the moderation platform

**Comment by AudreyTheIndustrious** [comment]
DD photo shoot, C&A branding content and content for dynamic IG post integration

**Comment by AudreyTheIndustrious** [comment]
is the digital signage part complete or is there more to do here? I think you took this on and I lost track of where it's at.

**Comment by AndyTheIndustrious** [comment]
All complete. We have the software delivered and just need to install it.

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Mar 11, 2018, at 5:39 AM, Audrey Sniezek <notifications@github.com<mailto:notifications@github.com>> wrote:


is the digital signage part complete or is there more to do here? I think you took this on and I lost track of where it's at.
