### ISSUE TITLE
Receive source content (hi-res) for grid 

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#31]

**Comment by AudreyTheIndustrious** [comment]
@saratheindustrious @AndyTheIndustrious any idea what this line item means? is this the content for DD or shelfmaster or?

**Comment by saratheindustrious** [comment]
I don't know. Where did it come from?

Maybe it could mean the images for the Instagram grid (which I just pulled from the web). As long as they are okay with what I pulled we would be good there. _But_ I'm not 100% sure that's what this note means.

**Comment by AndyTheIndustrious** [comment]
I’m going to go with that.  I wrote it and I believe that’s what I meant.

So let’s close this out.

Thank you.

**Comment by AudreyTheIndustrious** [comment]
Thanks!

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com
