### ISSUE TITLE
Schedule photo shoot (#14)

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#41]
related to issue Photographer, shop photo shoot #2 and Schedule photo shoot #14

**Comment by AudreyTheIndustrious** [comment]
@AndyTheIndustrious reminder to get David on the calendar for the Mar 14th photoshoot.

**Comment by AndyTheIndustrious** [comment]
Complete.  We will see what he says.

Thank you!

Andy
