### ISSUE TITLE
WttW user interface updates to support Mobile Shopping List functionality review

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#49]
We have the latest design from our creative designer, Sara. You can find the wttw-mobile-cr4.psd in your Dropbox folder.

Also attached a reference of what it looks like. Please find the background video for C&A Famous here: https://www.dropbox.com/s/0tamw287dlrluxj/cafamous-background.mov?dl=0

**Comment by saratheindustrious** [comment]
We should bring this up during the Wed 14Feb to see if he has any feedback.

**Comment by AudreyTheIndustrious** [comment]
we will review this in Tuesday Feb 26 meeting.
