### ISSUE TITLE
Provide test equipment to The Industrious

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#75]

**Comment by AudreyTheIndustrious** [comment]
@AndyTheIndustrious Are we waiting on any other test hardware? You already have 1 computer for WttW and 1 for Browse C&A, plus, we received the 23" from Robin.

**Comment by AndyTheIndustrious** [comment]
Not awaiting any further test hardware.  As soon as the scanner is certified, we need to order (12) and get them to Bonn for the install.

Thank you.

Andy
