### ISSUE TITLE
Receive final content for lounge instance

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#78]
3 calls to action:
1. scan barcode
2. sustainability video
3. watch kids video

**Comment by AudreyTheIndustrious** [comment]
@AndyTheIndustrious @saratheindustrious Do we have all of the video content for this now? We received approval to use Foundation video.

**Comment by AndyTheIndustrious** [comment]
I think @Sara Giessen<mailto:sara@wearetheindustrious.com> still needs copy?

**Comment by saratheindustrious** [comment]
Do we have the foundation video asset? I haven't seen that come through. And are we anticipating a sustainability video?

We are still waiting on some copy for the sustainability section. Latest copy doc is in 00_Reference/Copy

**Comment by AudreyTheIndustrious** [comment]
What part of the sustainability copy exactly? Should I request 2 videos or just the foundation video and?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
[Missing sustainability copy is highlighted here.](https://www.dropbox.com/s/e9m049b84iztbbs/18-0301-copy.xlsx?dl=0) Design/01_Assets/Copy

I believe the foundation video is what will play when you hit the foundation photo (bottom right on the home screen.)
![18-0301-browse_landing](https://user-images.githubusercontent.com/36420298/36912032-73d1a766-1e13-11e8-96fa-a333139c053b.jpg)

We have a space for a sustainability video (3rd callout in this screen grab) but I don't know if they have a video they would want to show.
![18-0301-browse_sustainability](https://user-images.githubusercontent.com/36420298/36912028-6ef19990-1e13-11e8-853e-7e79799eee70.jpg)

**Comment by AudreyTheIndustrious** [comment]
@saratheindustrious I believe we have this resolved now. I'm closing it out. I know you have a fit and finish item with ngoar, but otherwise, if you think this is not resolved, please reopen.
