### ISSUE TITLE
confirm the scanner Hardware

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#84]

**Comment by AndyTheIndustrious** [comment]
Hello!

Thank you for getting this in the tracker.

We need to add the scanner issue (represented by this ticket) to the list of discussion items for the Friday call with Robin.  How do we do that safely please?

Andy

**Comment by AndyTheIndustrious** [comment]
I’ve got it noted in the list for him.

From: Andy Austin
Sent: Thursday, February 8, 2018 11:18 AM
To: TheIndustrious/CandA <reply@reply.github.com>
Cc: Audrey Sniezek <Audrey@wearetheindustrious.com>
Subject: RE: [TheIndustrious/CandA] confirm the scanner Hardware (#84)

Hello!

Thank you for getting this in the tracker.

We need to add the scanner issue (represented by this ticket) to the list of discussion items for the Friday call with Robin.  How do we do that safely please?

Andy

**Comment by AudreyTheIndustrious** [comment]
Is Robin ok with the scanner option you presented despite not having a serial cable? Can I close this ticket? I have another ticket open regarding the reimbursement. Is there anything more we need to track for the scanner?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Hi there.

He loves the scanner.  I need to order another one to be at my office for when I return for testing with the cables that are already at my office when I return.

Thank you for closing this out.

Andy

**Comment by AudreyTheIndustrious** [comment]
Great. I’ll mark this as done. Unless you want me to track the ordering of another scanner. 😊

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AudreyTheIndustrious** [comment]
Andy needs to buy one more scanner, but Robin approves of the model. closing this out.

**Comment by AndyTheIndustrious** [comment]
I have told @Siri to tell me to buy another scanner tomorrow morning.

I hope that works.

Andy

**Comment by AndyTheIndustrious** [comment]
I bought the scanner for me to test with in my office.  It will arrive before I get home and I’ll test it with the cables that are on the way.

Thank you.

Andy
