### ISSUE TITLE
Evaluate new GPIO plan

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#9]

**Comment by AudreyTheIndustrious** [comment]
What's happening here?

**Comment by AndyTheIndustrious** [comment]
Hello!  I forgot to mention this on our call today.

Robin likes all of the Discover Digital Interactive concepts.  The large screen concept is approved.  For the touch panel, he chose option 4.

@Audrey Sniezek<mailto:Audrey@wearetheindustrious.com> – once @Sara Giessen<mailto:sara@wearetheindustrious.com> completes the full-size render of that, then we should speak with the vendor.  Would be great to call the vendor Thrusday night if Sara is able to complete the asset by then.

Thank you!

Andy

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious What does "full size render" mean and who is the vendor?

**Comment by AndyTheIndustrious** [comment]
Good morning!

I mean it would be a render that is print-ready at the exact measurements from the PDF of the visible area of the touch surface.  15 ¾” by 8 11/16” please.

The vendor is TSI Touch, but they are outsourcing manufacturing to Boyd Sign Systems.

@Audrey Sniezek<mailto:Audrey@wearetheindustrious.com> – we should schedule a call please with Aaron at TSI Touch (aaronm@tsitouch.com<mailto:aaronm@tsitouch.com>) and John (jbaggotgt@comqi.com<mailto:jbaggotgt@comqi.com>) at ComQi.  They are both east coast.  I’m avaialble on Thursday from noon to 5:00 pm CET for calls.

I’m also going to try to get out of going to Bonn tomorrow which would open up my entire day for calls.

Thank you!

Andy

**Comment by AndyTheIndustrious** [comment]
What would you like the title of this call to be? And is the agenda to discuss the measurements, the install, design, or is this a meet and greet general conversation?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

From: Andy Austin
Sent: Tuesday, February 20, 2018 12:16 AM
To: TheIndustrious/CandA <reply@reply.github.com>; TheIndustrious/CandA <CandA@noreply.github.com>; Audrey Sniezek <Audrey@wearetheindustrious.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [TheIndustrious/CandA] Evaluate new GPIO plan (#9)

Good morning!

I mean it would be a render that is print-ready at the exact measurements from the PDF of the visible area of the touch surface.  15 ¾” by 8 11/16” please.

The vendor is TSI Touch, but they are outsourcing manufacturing to Boyd Sign Systems.

@Audrey Sniezek<mailto:Audrey@wearetheindustrious.com> – we should schedule a call please with Aaron at TSI Touch (aaronm@tsitouch.com<mailto:aaronm@tsitouch.com>) and John (jbaggotgt@comqi.com<mailto:jbaggotgt@comqi.com>) at ComQi.  They are both east coast.  I’m avaialble on Thursday from noon to 5:00 pm CET for calls.

I’m also going to try to get out of going to Bonn tomorrow which would open up my entire day for calls.

Thank you!

Andy

**Comment by AudreyTheIndustrious** [comment]
Can you confirm John’s email? The meeting I sent was returned undeliverable.

Your message to jbaggotgt@comqi.com<mailto:jbaggotgt@comqi.com> couldn't be delivered.

jbaggotgt wasn't found at comqi.com.



Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
That's a terrible fat finger I did. I'm sorry.

It's jbaggott.

Andy


Andy Austin
President / The Industrious
mobile // +1.323.736.2121
mobile // +44.(0)7454.572.928

________________________________
