### ISSUE TITLE
Design DD external touchpad 

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/CandA#97]
Design the image that will be “frosted” onto the inside of the glass of the attached item?  It’s not elegant, but if it works we will endeavor to make it look better in future phases.

The entire left hemisphere of the glass is a “go left” signal.  The entire right hemisphere of the glass is a “go right” signal.  Either “button” (left or right) will interrupt the current play and go straight into looking at garments.

**Comment by saratheindustrious** [comment]
Questions for @AndyTheIndustrious :
- Is there a reason you're describing it as a "hemisphere"? Is it a rounded screen?
- Should the design be 16:9? I think so but the "inches" on the construction doc is making me unsure
- Will the creative this is changing be on the same screen as the buttons or is it on a different screen elsewhere?
- Is "looking at garments" literally just product images or is it more like hero looks?
- What is the timeline/review process?

**Comment by saratheindustrious** [comment]
Here are some comps for the different states of this interactive. @AndyTheIndustrious please let me know if you have any feedback or would like to discuss before we share with Robin on Monday.

Presentation deck here: https://www.dropbox.com/s/0knwg26dwsm6oq6/18-0216-CA-CR5.pptx?dl=0

JPGs here: https://www.dropbox.com/sh/47ut9cm68hnksy0/AAB40IbBDwOiNCOVAVFfBNO7a?dl=0

**Comment by AndyTheIndustrious** [comment]
OMG.  It’s so good.

Option 4 is so sweet.

I did confirm with ComQi that we can do what you are illustrating.  So let’s go with this to Robin.  I don’t have any changes to recommend.

Thank you!

Andy

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious How should we share these comps with Robin? Is there a time we could walk him through it or do you want to just send it via email?

https://www.dropbox.com/s/0knwg26dwsm6oq6/18-0216-CA-CR5.pptx?dl=0

**Comment by AndyTheIndustrious** [comment]
Hello!

I’d like to review these with him on the 9:30 am EST call that we have today.

We need to knock out:

  1.  What we learned from the big installation meeting
  2.  Copy and translations
  3.  Assets for WttW
  4.  Assets for Browse C&A
  5.  This button creative
  6.  Installation planning

Audrey – would you please make sure that all of this is covered on the agenda in addition to whatever you may already have?

Thank you very much you guys.  Looking forward to the call.

Andy

**Comment by AudreyTheIndustrious** [comment]
We didn’t review them the comps in the meeting, Andy, are you going to email them to him for review? Or were you able to discuss prior to our call?


Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Good morning.

We did discuss these prior to the call and he loved the DD main screen and chose option 4 for the control box.

I think this is being tracked in another ticket as well?  I put that information somewhere (although it might have been in a straight e-mail or in Skype.)

Thank you!

Andy

**Comment by saratheindustrious** [comment]
Here is the design for the button. It's a large (300MB) file.
https://www.dropbox.com/s/4qtfdr5ye23x6qs/DD-Touch.pdf?dl=0

**Comment by AudreyTheIndustrious** [comment]
Is this a public link I can sent to TSI Touch?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Yes
