### ISSUE TITLE
Add QR code functionality to product details on Browse C&A

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/CandA#99]
We need Ngoar to add QR codes to each product in Browse C&A.

**Comment by saratheindustrious** [comment]
![18-0219-browse_overlay](https://user-images.githubusercontent.com/36420298/36392596-03969ebc-157a-11e8-9275-2679c08de5e2.jpg)

@AndyTheIndustrious Let me know what you think of this. Once it's approved and Ngoar is on board I will update the PSD on their Dropbox.

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious Tagging you again to bump this up in your feed.

**Comment by AndyTheIndustrious** [comment]
Love it. Let's move forward with this. I'll share with Ngoar tomorrow.
